version: '3.3'

services:
  mongo:
    image: mongo:5
    container_name: notification-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: notification
    volumes:
      - ./database:/database
      - ./.db-data/mongodb:/data/db
      - ./.db-data/mongoconfig:/data/configdb
    ports:
      - 27017:27017
    command: mongod --quiet --logpath /dev/null
