# Install package dependencies
FROM node:16-alpine AS dependency

WORKDIR /notification

COPY package*.json ./
RUN npm ci

# Build source
FROM dependency AS base
COPY . .

# Build source
FROM base AS build
RUN npm run build:notification

# Ship compiled sources
FROM dependency

COPY --from=build /notification/dist ./dist
COPY ./i18n/ ./i18n/

RUN npm prune --production

EXPOSE 3000
ENV NO_COLOR=true
ARG COMMIT_HASH
ENV COMMIT_HASH=$COMMIT_HASH

CMD ["npm", "run", "start:notification:prod"]
